### PR TITLE
🤖 use a BroadcastReceiver instead of an IntentService to receive noti…

### PR DESCRIPTION
**Pull request by calypsow777**
…fs in bg

I've changed GeofenceTransitionsIntentService.java to use a BroadcastReceiver instead of an IntentService.
The package didn't work when the app was in bg/killed because of this:
image

### CODE REVIEW

**Review by gusilveiramp — APPROVED** [review]
Tested and approved.

**Comment by flache** [comment]
Looks good. So, when is this going to be merged?

**Comment by mikaelengstrom** [comment]
@michaelmika - Can you merge this?

**Comment by michaelmika** [comment]
Nice! Thanks for your effort!

**Pull request merged**
